spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ferouk_art
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
  admin:
    username: admin
    password: admin

aws:
  region: eu-central-1
  credentials:
    access-key: AKIAQWHCQGELHWCYM2Y6
    secret-key: 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
  s3:
    bucket-name: flashmenu