spring:
  datasource:
    url: ${DB_URL}           # jdbc:postgresql://<rds-endpoint>:5432/<db-name>
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: ${JWT_EXPIRATION:86400000}
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

aws:
  region: ${AWS_REGION}                     # e.g. eu-west-1
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: flashmenu
